### ISSUE TITLE
Need to include examples of tests

### ISSUE THREAD

**Issue by betakuwe** [betakuwe/sicp-js-tools#2]
This repo needs examples of code being tested. For example, checking that a random number generator generates valid results by testing it `n` number of times.

**Comment by StrwBrriShrtcke** [comment]
Hi! Can I add an example of a random die generator and its test function where it tests whether the random number generator gives an invalid results using a sample of for example, 2000 times.

**Comment by betakuwe** [comment]
Sounds good to me. Please go ahead.
